### ISSUE TITLE
请问加载静态地图如何自行切片，并分片加载？

### ISSUE THREAD

**Issue by blucechen** [anzhihun/OpenLayers3Primer#6]
您[这里](http://weilin.me/ol3-primer/ch05/05-05.html)写了 `对于图片比较大的情况，可以自行切片，然后分片加载，从而拼成一整张地图` ，请问您是如何进行的？我个人想到的是利用多图层叠加，也就是生成了多个layer，显示效果就是一个完整的地图，但是这样做会造成图层数量可能非常的多。请问您是有什么其他方法实现吗？

**Comment by anzhihun** [comment]
切片不是多图层叠加。切片工具比较多，可以用参见https://blog.csdn.net/renjianhhong/article/details/63688401
