### ISSUE TITLE
急求，遇到查询wfs跨域的问题

### ISSUE THREAD

**Issue by shaoxh** [anzhihun/OpenLayers3Primer#7]
在第12.1.3章节，我通过html访问geoserver中的内容，遇到了前端报错： No 'Access-Control-Allow-Origin' header is present on the requested resource。
我是在tomcat中启动的geoserver，给的8080端口。
另外新建了一个工程，使用openlayers加载地图，端口8008，把geoserver里面发布的矢量地图加载到openlayers用的OSM地图上面。
但是就遇到了上面的问题，具体报错信息：Access to XMLHttpRequest at 'http://localhost:8080/geoserver/wfs?service=wfs&version=1.1.0&request=GetFeature&typeNames=tiger:poi&outputFormat=application/json&srs=EPSG:4326' from origin 'http://localhost:8008' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

我修改了8080这个端口的tomcat的web.xml文件，加了如下的配置：
<filter>
    <filter-name>CorsFilter</filter-name>
    <filter-class>org.apache.catalina.filters.CorsFilter</filter-class>
    <init-param>
        <param-name>cors.allowed.origins</param-name>
        <param-value>http://localhost:8008</param-value>
    </init-param>
    <init-param>
        <param-name>cors.allowed.methods</param-name>
        <param-value>GET,POST,HEAD,OPTIONS,PUT</param-value>
    </init-param>
    <init-param>
        <param-name>cors.allowed.headers</param-name>
        <param-value>*</param-value>
    </init-param>
    <init-param>
        <param-name>cors.exposed.headers</param-name>
        <param-value>Access-Control-Allow-Origin,Access-Control-Allow-Credentials</param-value>
    </init-param>
    <init-param>
        <param-name>cors.support.credentials</param-name>
        <param-value>false</param-value>
    </init-param>
 
</filter>
<filter-mapping>
    <filter-name>CorsFilter</filter-name>
    <url-pattern>/*</url-pattern>
</filter-mapping>
但是仍然不能解决问题。求解答！

**Comment by anzhihun** [comment]
请参见12.1.1章节的跨域配置，注意tomcat的版本号
