### ISSUE TITLE
4.5.3自适应区域

### ISSUE THREAD

**Issue by 412799755** [anzhihun/OpenLayers3Primer#8]
function fitToChengdu() {
          // 让地图最大化完全地显示区域[104, 30.6, 104.12, 30.74]
          map.getView().fit([104, 30.6, 104.12, 30.74], map.getSize());
      }
查了一下API fit函数的传参第二个参数应该是{size:map.getSize()}的形式

**Comment by SheldonJiangHanbao** [comment]
谢谢😜------------------ 原始邮件 ------------------
发件人: "Luo Yu"<notifications@github.com>
发送时间: 2019年9月26日(星期四) 上午10:23
收件人: "anzhihun/OpenLayers3Primer"<OpenLayers3Primer@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [anzhihun/OpenLayers3Primer] 4.5.3自适应区域 (#8)



function fitToChengdu() {
 // 让地图最大化完全地显示区域[104, 30.6, 104.12, 30.74]
 map.getView().fit([104, 30.6, 104.12, 30.74], map.getSize());
 }
 查了一下API fit函数的传参第&#x4E8C;个参数应该是{size:map.getSize()}的形式
 
&mdash;

**Comment by anzhihun** [comment]
感谢，现在这个教程有点跟不上最新ol3版本的接口啊。
